function FCArticulationDef_ValueTests_ItemNo1(articdef)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "AboveSymbolChar", 46)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AboveUsesMain", true)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AlwaysPlaceOutsideStaff", false)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AttachToTopNote", false)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AttackIsPercent", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "AutoPosSide", finale.ARTPOS_AUTO_NOTESTEM)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "AvoidStaffLines", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BelowSymbolChar", 46)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "BelowUsesMain", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BottomAttack", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BottomDuration", 40)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "BottomVelocity", 0)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "CenterHorizontally", true)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "CopyMainSymbol", false)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "CopyMainSymbolHorizontally", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "DefaultVerticalPos", 16)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "DurationIsPercent", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedHandleHorizontalOffset", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedHandleVerticalOffset", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolChar", 46)
   StringValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolFont", "Maestro")
   BoolValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolIsShape", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolShapeID", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "FlippedSymbolSize", 24)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "InsideSlurs", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainHandleHorizontalOffset", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainHandleVerticalOffset", -4)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolChar", 46)
   StringValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolFont", "Maestro")
   BoolValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolIsShape", false)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolShapeID", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "MainSymbolSize", 24)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "OnScreenOnly", false)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "Playback", true)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "TopAttack", 0)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "TopDuration", 40)
   NumberValuePropertyTest(articdef, "FCArticulationDef", "TopVelocity", 0)
   BoolValuePropertyTest(articdef, "FCArticulationDef", "VelocityIsPercent", false)
end


-- Call:
local articdef = finale.FCArticulationDef()
AssureTrue(articdef:Load(1))
FCArticulationDef_ValueTests_ItemNo1(articdef)
