function FCRepeatPrefs_ValueTests_ItemNo1(repeatprefs)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "AfterClefSpace", 64)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "AfterKeySpace", 47)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "AfterTimeSpace", 49)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "BackToBackStyle", finale.REPBACKTOBACK_THIN)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "BackwardSpace", 11)
   BoolValuePropertyTest(repeatprefs, "FCRepeatPrefs", "DotAfterNumber", true)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingBackHookLength", 1)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingBracketHeight", 96)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingFrontHookLength", 72)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingHorizontalText", 36)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingInsetEnd", 3)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingInsetStart", 2)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingLineThickness", 224)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "EndingVerticalText", 24)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "ForwardSpace", 14)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "HeavyLineThickness", 832)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "MaxPasses", 20)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "SpaceBetweenLines", 768)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "ThinLineThickness", 115)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "VerticalBottomDotAdjustment", -2)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "VerticalTopDotAdjustment", -1)
   NumberValuePropertyTest(repeatprefs, "FCRepeatPrefs", "WingStyle", finale.REPWING_NONE)
end


-- Call:
local repeatprefs = finale.FCRepeatPrefs()
AssureTrue(repeatprefs:Load(1), "FCRepeatPrefs:Load()")
FCRepeatPrefs_ValueTests_ItemNo1(repeatprefs)
