function FCSmartShape_ValueTests_ItemNo1(smartshape)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "AvoidAccidentals", finale.SS_AUTOSTATE)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "BeatAttached", true)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "EngraverSlur", finale.SS_AUTOSTATE)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "EntryBased", false)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "LineID", 0)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "MaintainAngle", false)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "MakeHorizontal", true)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "PresetShape", true)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "ShapeType", finale.SMARTSHAPE_CRESCENDO)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "Visible", true)
    local left_seg = smartshape:GetTerminateSegmentLeft()
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "BreakOffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "BreakOffsetY", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint1OffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint1OffsetY", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint2OffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint2OffsetY", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "EndpointOffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "EndpointOffsetY", -139)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "EntryNumber", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "Measure", 25)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "MeasurePos", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "NoteID", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "Staff", 3)
    local right_seg = smartshape:GetTerminateSegmentRight()
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "BreakOffsetX", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "BreakOffsetY", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint1OffsetX", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint1OffsetY", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint2OffsetX", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint2OffsetY", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "EndpointOffsetX", 36)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "EndpointOffsetY", -139)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "EntryNumber", 2048)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "Measure", 26)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "MeasurePos", 2048)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "NoteID", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "Staff", 3)
end


-- Call:
local smartshape = finale.FCSmartShape()
AssureTrue(smartshape:Load(1), "FCSmartShape:Load(1)")
FCSmartShape_ValueTests_ItemNo1(smartshape)


function FCSmartShape_ValueTests_ItemNo2(smartshape)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "AvoidAccidentals", finale.SS_AUTOSTATE)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "BeatAttached", false)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "EngraverSlur", finale.SS_AUTOSTATE)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "EntryBased", true)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "LineID", 0)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "MaintainAngle", true)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "MakeHorizontal", false)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "PresetShape", true)
    NumberValuePropertyTest(smartshape, "FCSmartShape", "ShapeType", finale.SMARTSHAPE_SLURAUTO)
    BoolValuePropertyTest(smartshape, "FCSmartShape", "Visible", true)
    local left_seg = smartshape:GetTerminateSegmentLeft()
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "BreakOffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "BreakOffsetY", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint1OffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint1OffsetY", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint2OffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "ControlPoint2OffsetY", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "EndpointOffsetX", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "EndpointOffsetY", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "EntryNumber", 294)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "Measure", 25)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "MeasurePos", 294)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "NoteID", 0)
    NumberValuePropertyTest(left_seg, "FCSmartShapeSegment", "Staff", 2)
    local right_seg = smartshape:GetTerminateSegmentRight()
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "BreakOffsetX", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "BreakOffsetY", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint1OffsetX", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint1OffsetY", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint2OffsetX", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "ControlPoint2OffsetY", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "EndpointOffsetX", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "EndpointOffsetY", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "EntryNumber", 299)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "Measure", 26)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "MeasurePos", 299)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "NoteID", 0)
    NumberValuePropertyTest(right_seg, "FCSmartShapeSegment", "Staff", 2)
end


-- Call:
local smartshape = finale.FCSmartShape()
AssureTrue(smartshape:Load(2), "FCSmartShape:Load(2)")
FCSmartShape_ValueTests_ItemNo2(smartshape)
