function FCMiscDocPrefs_ValueTests_ItemNo1(miscdocprefs)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "AbbreviateCommonTimeSig", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "AbbreviateCutTimeSig", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "AdjustDotForMultiVoices", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "AllowFloatingRests", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "AlwaysSlashGraceNote", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "AvoidSystemMarginCollisions", true)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "BeamSlopeStyle", finale.BEAMSLOPE_FLATTENSTANDARD)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "BeamThreeEights", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "BeamedCommonTimeEights", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ChordPlayback", true)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ClefResize", 75)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "CloseBarlineAtEnd", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "CloseBarlineAtSystem", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ConsolidateRestsAcrossLayers", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "CourtesyClefAtSystemEnd", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "CourtesyKeySigAtSystemEnd", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "CourtesyTimeSigAtSystemEnd", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "CrossStaffNotesInOriginal", true)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "CurveResolution", 32)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "DateFormat", finale.DATEFORMAT_SHORT)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "DefaultClefIndex", 0)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "DisplayAllBarlines", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "DisplayPartExpressions", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "DisplayReverseStemming", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ExtendBeamsOverRests", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ExtendSecondaryBeamsOverRests", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "FinalBarlineAtEnd", true)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "FretboardsResizeFraction", 1000000)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "GraceNotePlaybackDuration", 128)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "HalfStemsForBeamedRests", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "IncludeRestsInFour", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ItalicizeCapoChords", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "KeySigCancelOutgoing", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "KeySigModeChange", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "KeySigNaturalsInC", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "KeySigOnlyFirstSystem", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "KeySigPreserveOctave", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "LeftBarlineDisplayMultipe", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "LeftBarlineDisplaySingle", false)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "MaxBeamSlope", 12)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "NormalDefaultBarline", true)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "OnlyFirstSystemClef", false)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "PageMarginScope", finale.PAGEMARGINSCOPE_CURRENT)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "PickupDuration", 0)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "PrimaryBeamWithinSpace", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ScaleManualNotePositioning", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "SecondsInTimeStamp", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "ShowFretboards", true)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "SpecialExtractionID", 0)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "TextTabCharacters", 4)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "TimeSigCompositeDecimals", 6)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "UnderlineDepth", -2500)
   NumberValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "UnderlineThickness", 414)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "UseNoteShapes", false)
   BoolValuePropertyTest(miscdocprefs, "FCMiscDocPrefs", "UseStemConnections", true)
end


-- Call:
local miscdocprefs = finale.FCMiscDocPrefs()
AssureTrue(miscdocprefs:Load(1), "FCMiscDocPrefs:Load(1)")
FCMiscDocPrefs_ValueTests_ItemNo1(miscdocprefs)
