function FCTiePrefs_PropertyTests(prefs)
   BoolPropertyTest(prefs, "FCTiePrefs", "AfterMultipleDots")
   BoolPropertyTest(prefs, "FCTiePrefs", "AfterSingleDot")
   BoolPropertyTest(prefs, "FCTiePrefs", "AvoidStaffLines")
   NumberPropertyTest(prefs, "FCTiePrefs", "AvoidStaffLinesDistance", {-144, 0, 144})
   BoolPropertyTest(prefs, "FCTiePrefs", "AvoidStaffLinesOnly")
   BoolPropertyTest(prefs, "FCTiePrefs", "BeforeSingleAccidental")
   BoolPropertyTest(prefs, "FCTiePrefs", "BreakForKeySigs")
   BoolPropertyTest(prefs, "FCTiePrefs", "BreakForTimeSigs")
   BoolPropertyTest(prefs, "FCTiePrefs", "ChordDirectionOpposingSeconds")
   NumberPropertyTest(prefs, "FCTiePrefs", "ChordDirectionType", {finale.TIECHORDDIR_OUTSIDEINSIDE, finale.TIECHORDDIR_STEMREVERSAL, finale.TIECHORDDIR_SPLITEVENLY})
   NumberPropertyTest(prefs, "FCTiePrefs", "ExtraSystemStartSpace", {0, 12, 24, 35})
   BoolPropertyTest(prefs, "FCTiePrefs", "FixedInsetStyle")
   NumberPropertyTest(prefs, "FCTiePrefs", "KeySigLeftHorizontalOffset", {-144, 0, 144})
   NumberPropertyTest(prefs, "FCTiePrefs", "KeySigRightHorizontalOffset", {-144, 0, 144})
   NumberPropertyTest(prefs, "FCTiePrefs", "MixedStemDirectionType", {finale.TIEMIXEDSTEM_OVER, finale.TIEMIXEDSTEM_UNDER, finale.TIEMIXEDSTEM_OPPOSITEFIRSTSTEM})
   NumberPropertyTest(prefs, "FCTiePrefs", "SecondsPlacement", {finale.TIESECONDS_NONE, finale.TIESECONDS_SHIFTSTART,
            finale.TIESECONDS_SHIFTEND, finale.TIESECONDS_SHIFTBOTH })
   NumberPropertyTest(prefs, "FCTiePrefs", "SystemLeftHorizontalOffset", {-144, 0, 144})
   NumberPropertyTest(prefs, "FCTiePrefs", "SystemRightHorizontalOffset", {-144, 0, 144})
   NumberPropertyTest(prefs, "FCTiePrefs", "ThicknessLeft", {0, 12, 24})
   NumberPropertyTest(prefs, "FCTiePrefs", "ThicknessRight", {0, 12, 24})
   NumberPropertyTest(prefs, "FCTiePrefs", "TimeSigLeftHorizontalOffset", {-144, 0, 144})
   NumberPropertyTest(prefs, "FCTiePrefs", "TimeSigRightHorizontalOffset", {-144, 0, 144})
   NumberPropertyTest(prefs, "FCTiePrefs", "TipWidth", {0, 500, 20000})
   BoolPropertyTest(prefs, "FCTiePrefs", "UseInterpolation")
   BoolPropertyTest(prefs, "FCTiePrefs", "UseOuterPlacement")
   BoolPropertyTest(prefs, "FCTiePrefs", "UseTieEndStyle")
end

-- Call:
local prefs = finale.FCTiePrefs()
AssureTrue(prefs:Load(1))
FCTiePrefs_PropertyTests(prefs)
