function FCStaff_PropertyTests(staff)
   BoolPropertyTest(staff, "FCStaff", "AllowHiding")
   PropertyTest(staff, "FCStaff", "AltNotationDisplayOtherLayerNotes")
   PropertyTest(staff, "FCStaff", "AltNotationLayer")
   PropertyTest(staff, "FCStaff", "AltNotationStyle")
   PropertyTest(staff, "FCStaff", "BottomBarlineOffset")
   BoolPropertyTest(staff, "FCStaff", "BreakBarlines")
   BoolPropertyTest(staff, "FCStaff", "BreakRepeatBarlines")
   BoolPropertyTest(staff, "FCStaff", "BreakTablatureLines")
   PropertyTest(staff, "FCStaff", "CapoPosition")
   PropertyTest(staff, "FCStaff", "DefaultClef")
   BoolPropertyTest(staff, "FCStaff", "DisplayEmptyRests")
   BoolPropertyTest(staff, "FCStaff", "FlatBeams")
   PropertyTest(staff, "FCStaff", "FretInstrumentDefID")
   BoolPropertyTest(staff, "FCStaff", "FretLetters")
   PropertyTest(staff, "FCStaff", "HideMode")
   BoolPropertyTest(staff, "FCStaff", "IgnoreKeySig")
   BoolPropertyTest(staff, "FCStaff", "IndependentFont")
   BoolPropertyTest(staff, "FCStaff", "IndependentKeySig")
   BoolPropertyTest(staff, "FCStaff", "IndependentTimeSig")
   PropertyTest(staff, "FCStaff", "InstrumentUUID")
   PropertyTest(staff, "FCStaff", "LineCount")
   PropertyTest(staff, "FCStaff", "LowestFret")
   BoolPropertyTest(staff, "FCStaff", "NoKeySigShowAccidentals")
   PropertyTest(staff, "FCStaff", "NotationStyle")
   BoolPropertyTest(staff, "FCStaff", "NoteColors")   
   BoolPropertyTest(staff, "FCStaff", "RedisplayOtherLayerAccidentals")
   BoolPropertyTest(staff, "FCStaff", "ShowAugmentationDots")
   BoolPropertyTest(staff, "FCStaff", "ShowBarlines")
   BoolPropertyTest(staff, "FCStaff", "ShowChords")
   BoolPropertyTest(staff, "FCStaff", "ShowClefs")
   BoolPropertyTest(staff, "FCStaff", "ShowFretboards")
   BoolPropertyTest(staff, "FCStaff", "ShowKeySignatures")
   BoolPropertyTest(staff, "FCStaff", "ShowLyrics")
   BoolPropertyTest(staff, "FCStaff", "ShowMeasureNumbers")
   BoolPropertyTest(staff, "FCStaff", "ShowNoteShapes")
   BoolPropertyTest(staff, "FCStaff", "ShowOnlyFirstMeasureClef")
   BoolPropertyTest(staff, "FCStaff", "ShowPartStaffNames")
   BoolPropertyTest(staff, "FCStaff", "ShowRepeats")
   BoolPropertyTest(staff, "FCStaff", "ShowRests")
   BoolPropertyTest(staff, "FCStaff", "ShowScoreStaffNames")
   BoolPropertyTest(staff, "FCStaff", "ShowStaffLines")
   BoolPropertyTest(staff, "FCStaff", "ShowStems")
   BoolPropertyTest(staff, "FCStaff", "ShowTextRepeats")
   BoolPropertyTest(staff, "FCStaff", "ShowTies")
   BoolPropertyTest(staff, "FCStaff", "ShowTimeSignatures")
   BoolPropertyTest(staff, "FCStaff", "ShowTuplets")
   NumberPropertyTest(staff, "FCStaff", "TopBarlineOffset", {-301, 0, 101})
   PropertyTest(staff, "FCStaff", "TransposeAlteration")
   PropertyTest(staff, "FCStaff", "TransposeChromatic")
   PropertyTest(staff, "FCStaff", "TransposeClefIndex")
   PropertyTest(staff, "FCStaff", "TransposeInterval")
   PropertyTest(staff, "FCStaff", "TransposeSimplifyKey")
   PropertyTest(staff, "FCStaff", "TransposeUseClef")
   NumberPropertyTest(staff, "FCStaff", "VerticalFretOffset", {-302, 0, 102})
end


-- Call:
local staff = finale.FCStaff()
AssureTrue(staff:Load(1), "FCStaffStyleDef:Load()")
FCStaff_PropertyTests(staff)
