function FCMusicCharacterPrefs_PropertyTests(mcharprefs)
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "DefaultStemLift", {-257, 0, 257})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Horizontal16thFlagDown", {-301, 0, 301})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Horizontal16thFlagUp", {-302, 0, 302})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "HorizontalFirstFlagDown", {-308, 0, 308})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "HorizontalFirstFlagUp", {-303, 0, 303})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "HorizontalSecondFlagDown", {-304, 0, 304})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "HorizontalSecondFlagUp", {-305, 0, 305})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "HorizontalStraightFlagDown", {-306, 0, 306})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "HorizontalStraightFlagUp", {-307, 0, 307})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Symbol128thRest", {61, 111, 311})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Symbol16thFlagDown", {61, 112, 312})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Symbol16thFlagUp", {61, 113, 313})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Symbol16thRest", {61, 114, 314})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Symbol32ndRest", {61, 115, 315})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Symbol64thRest", {61, 116, 316})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Symbol8thRest", {61, 117, 317})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolAugmentationDot", {61, 118, 318})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolBackwardRepeatDot", {62, 152, 352})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolBrevisNotehead", {61, 119, 319})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolBrevisRest", {61, 120, 320})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolBrevisSlashDiamond", {61, 121, 321})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolChordDoubleFlat", {61, 122, 322})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolChordDoubleSharp", {61, 123, 323})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolChordFlat", {61, 124, 324})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolChordNatural", {61, 125, 325})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolChordSharp", {61, 126, 326})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolDefaultMeasureRest", {61, 127, 327})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolDoubleFlat", {61, 128, 328})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolDoubleSharp", {61, 129, 329})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolFirstFlagDown", {61, 130, 330})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolFirstFlagUp", {61, 131, 331})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolFlat", {61, 132, 332})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolForwardRepeatDot", {61, 151, 351})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolHalfNotehead", {61, 133, 333})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolHalfRest", {61, 134, 334})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolHalfSlashDiamond", {61, 135, 335})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolKeyDoubleFlat", {61, 136, 336})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolKeyDoubleSharp", {61, 137, 337})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolKeyFlat", {61, 138, 338})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolKeyNatural", {61, 139, 339})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolKeySharp", {61, 140, 340})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolLargeSlash", {61, 141, 341})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolNatural", {61, 142, 342})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolOneBarRepeat", {61, 143, 343})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolParDoubleFlat", {61, 144, 344})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolParDoubleSharp", {61, 145, 345})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolParFlat", {61, 146, 346})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolParNatural", {61, 147, 347})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolParSharp", {61, 148, 348})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolQuarterNotehead", {61, 149, 349})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolQuarterRest", {61, 150, 350})   
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolSecondFlagDown", {61, 152, 352})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolSecondFlagUp", {61, 153, 353})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolSharp", {61, 154, 354})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolSmallSlash", {61, 155, 355})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolStraightFlagDown", {61, 156, 356})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolStraightFlagUp", {61, 157, 357})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolTimeSigPlusScore", {61, 158, 358})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolTwoBarRepeat", {61, 159, 359})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolWholeNotehead", {61, 160, 360})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolWholeRest", {61, 161, 361})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "SymbolWholeSlashDiamond", {61, 162, 362})
   BoolPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "UseStraightFlags")
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Vertical128thRest", {-331, 0, 331})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Vertical16thFlagDown", {-332, 0, 332})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Vertical16thFlagUp", {-333, 0, 333})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Vertical16thRest", {-334, 0, 334})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Vertical32ndRest", {-335, 0, 335})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Vertical64thRest", {-336, 0, 336})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "Vertical8thRest", {-337, 0, 337})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalFirstFlagDown", {-338, 0, 338})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalFirstFlagUp", {-339, 0, 339})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalFlagSpacing", {-340, 0, 340})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalHalfSlashStemLift", {-341, 0, 341})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalQuarterSlashBaseline", {-342, 0, 342})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalQuarterSlashStemLift", {-343, 0, 343})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalSecondFlagDown", {-344, 0, 344})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalSecondFlagUp", {-345, 0, 345})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalSecondaryGroupAdjust", {-346, 0, 346})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalStraightFlagDown", {-347, 0, 347})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalStraightFlagUp", {-348, 0, 348})
   NumberPropertyTest(mcharprefs, "FCMusicCharacterPrefs", "VerticalTwoMeasureRepeatOffset", {-349, 0, 349})
end


-- Call:
local mcharprefs = finale.FCMusicCharacterPrefs()
AssureTrue(mcharprefs:Load(1), "FCMusicCharacterPrefs:Load()")
FCMusicCharacterPrefs_PropertyTests(mcharprefs)

