function FCPageFormatPrefs_PropertyTests(pfprefs)
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "FirstPageTopMargin", {-100, 0, 99})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "FirstSystemDistance", {-98, 0, 101})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "FirstSystemLeft", {-95, 0, 105})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "FirstSystemTop", {-92, 0, 107})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "LeftPageBottomMargin", {-101, 0, 108})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "LeftPageLeftMargin", {-102, 0, 109})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "LeftPageRightMargin", {-103, 0, 110})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "LeftPageTopMargin", {-104, 0, 111})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "PageHeight", {100, 1000, 10000})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "PageScaling", {10, 100, 195})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "PageWidth", {102, 1002, 10002})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "RightPageBottomMargin", {-99, 0, 98})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "RightPageLeftMargin", {-97, 0, 97})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "RightPageRightMargin", {-95, 0, 96})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "RightPageTopMargin", {-95, 0, 95})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "SystemBottom", {-10, 0, 120})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "SystemDistanceBetween", {-20, 0, 250})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "SystemLeft", {-20, 0, 50})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "SystemRight", {-21, 0, 51})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "SystemScaling", {10, 100, 120})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "SystemStaffHeight", {1001, 1536, 4000})
   NumberPropertyTest(pfprefs, "FCPageFormatPrefs", "SystemTop", {-22, 0, 52})
   BoolPropertyTest(pfprefs, "FCPageFormatPrefs", "UseFacingPages")
   BoolPropertyTest(pfprefs, "FCPageFormatPrefs", "UseFirstPageTopMargin")
   BoolPropertyTest(pfprefs, "FCPageFormatPrefs", "UseFirstSystemMargins")
end


-- Call:
local pfprefsscore = finale.FCPageFormatPrefs()
AssureTrue(pfprefsscore:LoadScore(), "FCPageFormatPrefs::LoadScore()")
FCPageFormatPrefs_PropertyTests(pfprefsscore)
local pfprefsparts = finale.FCPageFormatPrefs()
AssureTrue(pfprefsparts:LoadParts(), "FCPageFormatPrefs::LoadParts()")
FCPageFormatPrefs_PropertyTests(pfprefsparts)
