function FCStaff_PropertyTests(staff)
   BoolPropertyTest(staff, "FCStaff", "AllowHiding")
   BoolPropertyTest(staff, "FCStaff", "AltNotationDisplayOtherLayerNotes")
   NumberPropertyTest(staff, "FCStaff", "AltNotationLayer", {1,2,3})
   NumberPropertyTest(staff, "FCStaff", "AltNotationStyle", { finale.ALTSTAFF_NORMAL,
        finale.ALTSTAFF_SLASHBEATS, finale.ALTSTAFF_RHYTHMIC,
        finale.ALTSTAFF_ONEBARREPEAT, finale.ALTSTAFF_TWOBARREPEAT,
        finale.ALTSTAFF_BLANKNOTATION } )
   NumberPropertyTest(staff, "FCStaff", "BottomBarlineOffset", { -299, 0, 299 } )
   BoolPropertyTest(staff, "FCStaff", "BreakBarlines")
   BoolPropertyTest(staff, "FCStaff", "BreakRepeatBarlines")
   BoolPropertyTest(staff, "FCStaff", "BreakTablatureLines")
   NumberPropertyTest(staff, "FCStaff", "CapoPosition", {0, 10, 17})
   NumberPropertyTest(staff, "FCStaff", "DefaultClef", {1,4, 10})
   BoolPropertyTest(staff, "FCStaff", "DisplayEmptyRests")
   BoolPropertyTest(staff, "FCStaff", "FlatBeams")
   NumberPropertyTest(staff, "FCStaff", "FretInstrumentDefID", {1, 10, 101})
   BoolPropertyTest(staff, "FCStaff", "FretLetters")
   NumberPropertyTest(staff, "FCStaff", "HideMode", { finale.STAFFHIDE_NORMAL, 
            finale.STAFFHIDE_SCORE, finale.STAFFHIDE_SCORE_AND_PARTS,
        finale.STAFFHIDE_CUTAWAY } )
   BoolPropertyTest(staff, "FCStaff", "IgnoreKeySig")
   BoolPropertyTest(staff, "FCStaff", "IndependentFont")
   BoolPropertyTest(staff, "FCStaff", "IndependentKeySig")
   BoolPropertyTest(staff, "FCStaff", "IndependentTimeSig")
   StringPropertyTest(staff, "FCStaff", "InstrumentUUID", {"a925648a-abc9-4dc7-a619-a6ce355ad33c"})
   NumberPropertyTest(staff, "FCStaff", "LineCount", {0, 1,5 })
   NumberPropertyTest(staff, "FCStaff", "LowestFret", {0, 2, 9})
   BoolPropertyTest(staff, "FCStaff", "NoKeySigShowAccidentals")
   NumberPropertyTest(staff, "FCStaff", "NotationStyle", {finale.STAFFNOTATION_NORMAL,
        finale.STAFFNOTATION_PERCUSSION, finale.STAFFNOTATION_TABLATURE} )   
   BoolPropertyTest(staff, "FCStaff", "RedisplayOtherLayerAccidentals")
   BoolPropertyTest(staff, "FCStaff", "ShowAugmentationDots")
   BoolPropertyTest(staff, "FCStaff", "ShowBarlines")
   BoolPropertyTest(staff, "FCStaff", "ShowChords")
   BoolPropertyTest(staff, "FCStaff", "ShowClefs")
   BoolPropertyTest(staff, "FCStaff", "ShowFretboards")
   BoolPropertyTest(staff, "FCStaff", "ShowKeySignatures")
   BoolPropertyTest(staff, "FCStaff", "ShowLyrics")
   BoolPropertyTest(staff, "FCStaff", "ShowMeasureNumbers")
   BoolPropertyTest(staff, "FCStaff", "ShowNoteColors")   
   BoolPropertyTest(staff, "FCStaff", "ShowNoteShapes")
   BoolPropertyTest(staff, "FCStaff", "ShowOnlyFirstMeasureClef")
   BoolPropertyTest(staff, "FCStaff", "ShowPartStaffNames")
   BoolPropertyTest(staff, "FCStaff", "ShowRepeats")
   BoolPropertyTest(staff, "FCStaff", "ShowRests")
   BoolPropertyTest(staff, "FCStaff", "ShowScoreStaffNames")
   BoolPropertyTest(staff, "FCStaff", "ShowStaffLines")
   BoolPropertyTest(staff, "FCStaff", "ShowStems")
   BoolPropertyTest(staff, "FCStaff", "ShowTextRepeats")
   BoolPropertyTest(staff, "FCStaff", "ShowTies")
   BoolPropertyTest(staff, "FCStaff", "ShowTimeSignatures")
   BoolPropertyTest(staff, "FCStaff", "ShowTuplets")
   NumberPropertyTest(staff, "FCStaff", "TopBarlineOffset", {-301, 0, 101})
   PropertyTest(staff, "FCStaff", "TransposeAlteration")
   PropertyTest(staff, "FCStaff", "TransposeChromatic")
   PropertyTest(staff, "FCStaff", "TransposeClefIndex")
   PropertyTest(staff, "FCStaff", "TransposeInterval")
   PropertyTest(staff, "FCStaff", "TransposeSimplifyKey")
   PropertyTest(staff, "FCStaff", "TransposeUseClef")
   NumberPropertyTest(staff, "FCStaff", "VerticalFretOffset", {-302, 0, 102})
end


-- Call:
local staff = finale.FCStaff()
AssureTrue(staff:Load(1), "FCStaffStyleDef:Load()")
FCStaff_PropertyTests(staff)
