function TestConstants_TIEMODTYPE_()
   NumberConstantTest(finale.TIEMODTYPE_TIEEND, "TIEMODTYPE_TIEEND", 0)
   NumberConstantTest(finale.TIEMODTYPE_TIESTART, "TIEMODTYPE_TIESTART", 1)
end

-- Test the constants:
TestConstants_TIEMODTYPE_()


function TestConstants_TIEMODDIR_()
   NumberConstantTest(finale.TIEMODDIR_AUTOMATIC, "TIEMODDIR_AUTOMATIC", 0)
   NumberConstantTest(finale.TIEMODDIR_OVER, "TIEMODDIR_OVER", 1)
   NumberConstantTest(finale.TIEMODDIR_UNDER, "TIEMODDIR_UNDER", 2)
end

-- Test the constants:
TestConstants_TIEMODDIR_()


function TestConstants_TIEMODSEL_()
   NumberConstantTest(finale.TIEMODSEL_DEFAULT, "TIEMODSEL_DEFAULT", 0)
   NumberConstantTest(finale.TIEMODSEL_ON, "TIEMODSEL_ON", 1)
   NumberConstantTest(finale.TIEMODSEL_OFF, "TIEMODSEL_OFF", 2)
end

-- Test the constants:
TestConstants_TIEMODDIR_()


function TestConstants_TIEMODCNCT_()
   NumberConstantTest(finale.TIEMODCNCT_NONE, "TIEMODCNCT_NONE", 0)
   NumberConstantTest(finale.TIEMODCNCT_ENTRYLEFT_NOTECENTER, "TIEMODCNCT_ENTRYLEFT_NOTECENTER", 1)
   NumberConstantTest(finale.TIEMODCNCT_ENTRYRIGHT_NOTECENTER, "TIEMODCNCT_ENTRYRIGHT_NOTECENTER", 2)
   NumberConstantTest(finale.TIEMODCNCT_NOTELEFT_NOTECENTER, "TIEMODCNCT_NOTELEFT_NOTECENTER", 3)
   NumberConstantTest(finale.TIEMODCNCT_NOTERIGHT_NOTECENTER, "TIEMODCNCT_NOTERIGHT_NOTECENTER", 4)
   NumberConstantTest(finale.TIEMODCNCT_NOTECENTER_NOTEBOTTOM, "TIEMODCNCT_NOTECENTER_NOTEBOTTOM", 5)
   NumberConstantTest(finale.TIEMODCNCT_NOTECENTER_NOTETOP, "TIEMODCNCT_NOTECENTER_NOTETOP", 6)
   NumberConstantTest(finale.TIEMODCNCT_DOTRIGHT_NOTECENTER, "TIEMODCNCT_DOTRIGHT_NOTECENTER", 7)
   NumberConstantTest(finale.TIEMODCNCT_ACCILEFT_NOTECENTER, "TIEMODCNCT_ACCILEFT_NOTECENTER", 8)
   NumberConstantTest(finale.TIEMODCNCT_ENTRYCENTER_NOTEBOTTOM, "TIEMODCNCT_ENTRYCENTER_NOTEBOTTOM", 9)
   NumberConstantTest(finale.TIEMODCNCT_ENTRYCENTER_NOTETOP, "TIEMODCNCT_ENTRYCENTER_NOTETOP", 10)
   NumberConstantTest(finale.TIEMODCNCT_NOTELEFT_NOTEBOTTOM, "TIEMODCNCT_NOTELEFT_NOTEBOTTOM", 11)
   NumberConstantTest(finale.TIEMODCNCT_NOTERIGHT_NOTEBOTTOM, "TIEMODCNCT_NOTERIGHT_NOTEBOTTOM", 12)
   NumberConstantTest(finale.TIEMODCNCT_NOTELEFT_NOTETOP, "TIEMODCNCT_NOTELEFT_NOTETOP", 13)
   NumberConstantTest(finale.TIEMODCNCT_NOTERIGHT_NOTETOP, "TIEMODCNCT_NOTERIGHT_NOTETOP", 14)
   NumberConstantTest(finale.TIEMODCNCT_SYSTEMEND, "TIEMODCNCT_SYSTEMEND", 15)
   NumberConstantTest(finale.TIEMODCNCT_SYSTEMSTART, "TIEMODCNCT_SYSTEMSTART", 16)
end

-- Test the constants:
TestConstants_TIEMODCNCT_()
