function TestConstants_ALIGNVERT()
    NumberConstantTest(finale.ALIGNVERT_ABOVEENTRY, "ALIGNVERT_ABOVEENTRY", 6)
    NumberConstantTest(finale.ALIGNVERT_ABOVE_STAFF_BASELINE, "ALIGNVERT_ABOVE_STAFF_BASELINE", 0)
    NumberConstantTest(finale.ALIGNVERT_ABOVE_STAFF_BASELINE_OR_ENTRY, "ALIGNVERT_ABOVE_STAFF_BASELINE_OR_ENTRY", 8)
    NumberConstantTest(finale.ALIGNVERT_BELOWENTRY, "ALIGNVERT_BELOWENTRY", 7)
    NumberConstantTest(finale.ALIGNVERT_BELOW_STAFF_BASELINE, "ALIGNVERT_BELOW_STAFF_BASELINE", 1)
    NumberConstantTest(finale.ALIGNVERT_BELOW_STAFF_BASELINE_OR_ENTRY, "ALIGNVERT_BELOW_STAFF_BASELINE_OR_ENTRY", 9)
    NumberConstantTest(finale.ALIGNVERT_BOTTOMNOTE, "ALIGNVERT_BOTTOMNOTE", 5)
    NumberConstantTest(finale.ALIGNVERT_CLICKPOS, "ALIGNVERT_CLICKPOS", 2)
    NumberConstantTest(finale.ALIGNVERT_STAFF_REFERENCE_LINE, "ALIGNVERT_STAFF_REFERENCE_LINE", 3)
    NumberConstantTest(finale.ALIGNVERT_TOPNOTE, "ALIGNVERT_TOPNOTE", 4)
end

-- Test the constants:
TestConstants_ALIGNVERT()


function TestConstants_ALIGNHORIZ()
   NumberConstantTest(finale.ALIGNHORIZ_AFTERCLEFKEYTIMEREPEAT, "ALIGNHORIZ_AFTERCLEFKEYTIMEREPEAT", 2)
   NumberConstantTest(finale.ALIGNHORIZ_CENTERALLNOTEHEADS, "ALIGNHORIZ_CENTERALLNOTEHEADS", 12)
   NumberConstantTest(finale.ALIGNHORIZ_CENTERBETWEENBARLINES, "ALIGNHORIZ_CENTERBETWEENBARLINES", 4)
   NumberConstantTest(finale.ALIGNHORIZ_CENTEROVERUNDERMUSIC, "ALIGNHORIZ_CENTEROVERUNDERMUSIC", 5)
   NumberConstantTest(finale.ALIGNHORIZ_CENTERPRIMARYNOTEHEAD, "ALIGNHORIZ_CENTERPRIMARYNOTEHEAD", 11)
   NumberConstantTest(finale.ALIGNHORIZ_CLICKPOS, "ALIGNHORIZ_CLICKPOS", 3)
   NumberConstantTest(finale.ALIGNHORIZ_LEFTBARLINE, "ALIGNHORIZ_LEFTBARLINE", 0)
   NumberConstantTest(finale.ALIGNHORIZ_LEFTOFALLNOTEHEAD, "ALIGNHORIZ_LEFTOFALLNOTEHEAD", 9)
   NumberConstantTest(finale.ALIGNHORIZ_LEFTOFPRIMARYNOTEHEAD, "ALIGNHORIZ_LEFTOFPRIMARYNOTEHEAD", 13)
   NumberConstantTest(finale.ALIGNHORIZ_RIGHTALLNOTEHEADS, "ALIGNHORIZ_RIGHTALLNOTEHEADS", 14)
   NumberConstantTest(finale.ALIGNHORIZ_RIGHTBARLINE, "ALIGNHORIZ_RIGHTBARLINE", 6)
   NumberConstantTest(finale.ALIGNHORIZ_STARTOFMUSIC, "ALIGNHORIZ_STARTOFMUSIC", 7)
   NumberConstantTest(finale.ALIGNHORIZ_STEM, "ALIGNHORIZ_STEM", 10)
   NumberConstantTest(finale.ALIGNHORIZ_TIMESIGSTART, "ALIGNHORIZ_TIMESIGSTART", 1)
end

-- Test the constants:
TestConstants_ALIGNHORIZ()


function TestConstants_EXPRJUSTIFY()
   NumberConstantTest(finale.EXPRJUSTIFY_CENTER, "EXPRJUSTIFY_CENTER", 1)
   NumberConstantTest(finale.EXPRJUSTIFY_LEFT, "EXPRJUSTIFY_LEFT", 0)
   NumberConstantTest(finale.EXPRJUSTIFY_RIGHT, "EXPRJUSTIFY_RIGHT", 2)
end

-- Test the constants:
TestConstants_EXPRJUSTIFY()
