function TestConstants_PARTWILLDISPLAY_()
   NumberConstantTest(finale.PARTDISP_ALLNOTES_IN_SINGLE_LAYER, "PARTDISP_ALLNOTES_IN_SINGLE_LAYER", 0)
   NumberConstantTest(finale.PARTDISP_SELECTED_NOTES_MULTIPLE_LAYERS, "PARTDISP_SELECTED_NOTES_MULTIPLE_LAYERS ", 1)
end

-- Test the constants:
TestConstants_PARTWILLDISPLAY_()

function TestConstants_VOICINGLAYERRULES_()
   NumberConstantTest(finale.VOICINGLAYERRULE_ALL_NOTES, "VOICINGLAYERRULE_ALL_NOTES", 0)
   NumberConstantTest(finale.VOICINGLAYERRULE_TOP_NOTE, "VOICINGLAYERRULE_TOP_NOTE ", 1)
   NumberConstantTest(finale.VOICINGLAYERRULE_BOTTOM_NOTE, "VOICINGLAYERRULE_BOTTOM_NOTE ", 2)
   NumberConstantTest(finale.VOICINGLAYERRULE_SELECTED_NOTES, "VOICINGLAYERRULE_SELECTED_NOTES ", 3)
end

-- Test the constants:
TestConstants_VOICINGLAYERRULES_()

function TestConstants_VOICINGCOUNTNOTES_()
   NumberConstantTest(finale.VCOUNTNOTES_FROM_THE_TOP, "VCOUNTNOTES_FROM_THE_TOP ", 1)
   NumberConstantTest(finale.VCOUNTNOTES_FROM_THE_BOTTOM, "VCOUNTNOTES_FROM_THE_BOTTOM ", 2)
end

-- Test the constants:
TestConstants_VOICINGCOUNTNOTES_()
