function TestConstants_MEASUREMENTUNIT_()
   NumberConstantTest(finale.MEASUREMENTUNIT_DEFAULT, "MEASUREMENTUNIT_DEFAULT", 0)
   NumberConstantTest(finale.MEASUREMENTUNIT_EVPUS, "MEASUREMENTUNIT_EVPUS", 1)
   NumberConstantTest(finale.MEASUREMENTUNIT_INCHES, "MEASUREMENTUNIT_INCHES", 2)
   NumberConstantTest(finale.MEASUREMENTUNIT_CENTIMETERS, "MEASUREMENTUNIT_CENTIMETERS", 3)
   NumberConstantTest(finale.MEASUREMENTUNIT_PICAS, "MEASUREMENTUNIT_PICAS", 5)
   NumberConstantTest(finale.MEASUREMENTUNIT_POINTS, "MEASUREMENTUNIT_POINTS", 4)
   NumberConstantTest(finale.MEASUREMENTUNIT_SPACES, "MEASUREMENTUNIT_SPACES", 6)
   NumberConstantTest(finale.MEASUREMENTUNIT_MILLIMETERS, "MEASUREMENTUNIT_MILLIMETERS", 100)
end

-- Test the constants:
TestConstants_MEASUREMENTUNIT_()
