function TestConstants_MEASUREMENTUNIT_()
   NumberConstantTest(finale.MEASUREMENTUNIT_DEFAULT, "MEASUREMENTUNIT_DEFAULT", 0)
   NumberConstantTest(finale.MEASUREMENTUNIT_EVPUS, "MEASUREMENTUNIT_EVPUS", 1)
   NumberConstantTest(finale.MEASUREMENTUNIT_INCHES, "MEASUREMENTUNIT_INCHES", 2)
   NumberConstantTest(finale.MEASUREMENTUNIT_CENTIMETERS, "MEASUREMENTUNIT_CENTIMETERS", 3)
   NumberConstantTest(finale.MEASUREMENTUNIT_PICAS, "MEASUREMENTUNIT_PICAS", 5)
   NumberConstantTest(finale.MEASUREMENTUNIT_POINTS, "MEASUREMENTUNIT_POINTS", 4)
   NumberConstantTest(finale.MEASUREMENTUNIT_SPACES, "MEASUREMENTUNIT_SPACES", 6)
   NumberConstantTest(finale.MEASUREMENTUNIT_MILLIMETERS, "MEASUREMENTUNIT_MILLIMETERS", 100)
end

-- Test the constants:
TestConstants_MEASUREMENTUNIT_()


function TestConstants_GRACEQUANTMODE_()
   NumberConstantTest(finale.GRACEQUANTMODE_ALLOW, "GRACEQUANTMODE_ALLOW", 0)
   NumberConstantTest(finale.GRACEQUANTMODE_REMOVE, "GRACEQUANTMODE_REMOVE", 1)
   NumberConstantTest(finale.GRACEQUANTMODE_CONVERT, "GRACEQUANTMODE_CONVERT", 2)
end

-- Test the constants:
TestConstants_GRACEQUANTMODE_()


function TestConstants_QUANTIZATIONMODE_()
   NumberConstantTest(finale.QUANTIZATIONMODE_NOTUPLETS, "QUANTIZATIONMODE_NOTUPLETS", 1)
   NumberConstantTest(finale.QUANTIZATIONMODE_MIXRHYTHMS, "QUANTIZATIONMODE_MIXRHYTHMS", 2)
   NumberConstantTest(finale.QUANTIZATIONMODE_SPACEEVENLY, "QUANTIZATIONMODE_SPACEEVENLY", 3)
end

-- Test the constants:
TestConstants_QUANTIZATIONMODE_()


function TestConstants_UNDOSTATE_()
   NumberConstantTest(finale.UNDOSTATE_OFF, "UNDOSTATE_OFF", -2)
   NumberConstantTest(finale.UNDOSTATE_SUSPENDED, "UNDOSTATE_SUSPENDED", -1)
   NumberConstantTest(finale.UNDOSTATE_DISABLED, "UNDOSTATE_DISABLED", 0)
   NumberConstantTest(finale.UNDOSTATE_ENABLED, "UNDOSTATE_ENABLED", 1)
end

-- Test the constants:
TestConstants_UNDOSTATE_()

